### ISSUE TITLE
Translate images during rendering process ?

### ISSUE THREAD

**Issue by chaiban** [thodan/bop_toolkit#10]
HI @thodan , Thank you for such a wonderful toolbox. 

I wanted to know, if there is a way to translate the images during rendering process?

Because, I am working on creating my own dataset using a 3 distinct models and all the images are placed at center of the image after rendering. For my application, I would like to place all objects in same image. If there is a translation, then it would be easier to concatenate all objects to single image. 

Any suggestions ?

If you have a different idea, I would gladly look into it.

Thank you for your suggestions.

**Comment by thodan** [comment]
Hi chaiban,
In https://github.com/thodan/bop_toolkit/blob/master/scripts/render_train_imgs.py#L170
you can replace view['R'] and view['t'] with any rotation matrix and translation vector. Hope this helps.
