### ISSUE TITLE
Questions about megapose dataset

### ISSUE THREAD

**Issue by parkjaewoo0611** [thodan/bop_toolkit#100]
Hi, Thanks for releasing great dataset, 

I am setting up a dataset following the guide provided at https://github.com/thodan/bop_toolkit/blob/master/docs/bop_challenge_2023_training_datasets.md, and I have two questions.

According to the guide, the .obj files downloaded from https://research.google/resources/datasets/scanned-objects-google-research/ are not centered at the origin. When I projected them in this state, they did not match the images. However, when I adjusted them to make the centroid the origin, they seemed to align better. Is this adjustment necessary?

When I adjust the centroid to the origin, the direction of the translation vector to the object seems correct, but the scale is off. When I scale the mesh by 0.1 as instructed in the guide, it appears too small. Are there any additional scale considerations I should be aware of? (I've already tried scaling from mm to m and vice versa, but the difference in scale seems more subtle than such large discrepancies, similar to the difference shown in the attached image.)

![image](https://github.com/thodan/bop_toolkit/assets/26773195/a32d14fe-b4d4-4967-a2d6-0d13726c3e3b)

**Comment by parkjaewoo0611** [comment]
1. centroid -> origin
2. scaling max(x, y, z) to 0.1 
resolves the issue. 
Since the problem has been resolved, close this issue.

**Comment by ylabbe** [comment]
Thanks a lot for pointing out that our instructions to scale the mesh are incorrect. See also #98.
