### ISSUE TITLE
why some datasets has no train images?

### ISSUE THREAD

**Issue by zeal-github** [thodan/bop_toolkit#11]
Hi, I download core datasets from the BOP2019 website. But after unzip this files, I found that hb_bop19 and itodd_full have no train sub-directory. Do these two datasets have no official training data?

**Comment by thodan** [comment]
Hello. Yes, that is right -- the currently provided versions of these datasets do not include the rendered training images. However, the images can be obtained using scripts/render_train_imgs.py
