### ISSUE TITLE
Why are these leaderboards missing?

### ISSUE THREAD

**Issue by zhimin-z** [thodan/bop_toolkit#119]
Such as https://bop.felk.cvut.cz/leaderboards/segmentation-unseen-bop23/tyo-l:
<img width="1071" alt="image" src="https://github.com/thodan/bop_toolkit/assets/8592144/8ebe264c-08da-4149-ad38-b4914246631d">

**Comment by thodan** [comment]
TYO-L is not one of the seven core datasets (https://bop.felk.cvut.cz/challenges/bop-challenge-2023/#datasets) and nobody has submitted any results for the "2D segmentation of unseen objects" task on this dataset yet.
