### ISSUE TITLE
Script for automatic calculation of  continous/discrete symmetries given a CAD model

### ISSUE THREAD

**Issue by monajalal** [thodan/bop_toolkit#121]
Is there a script to calculate the values for discrete symmetries or continuous symmetries for a CAD model?

![image](https://github.com/thodan/bop_toolkit/assets/1892917/662d0bc6-142e-4e3e-ac6f-f5d42df1a2eb)

Photo from this article https://www.mdpi.com/2075-1702/12/2/99

**Comment by thodan** [comment]
Hello, please see https://github.com/thodan/bop_toolkit/issues/50
