### ISSUE TITLE
3D bounding box labels around rendered image ?

### ISSUE THREAD

**Issue by chaiban** [thodan/bop_toolkit#13]
Hi @thodan ,

is there a script for 3D bounding box corner generation of rendered image ?
or 
any idea on how to generate 3d bbox corner labels ?
Thanks!
(sorry for stupid questions)

**Comment by thodan** [comment]
Hello, you can use function [transform_pts_Rt(pts, R, t)](https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/misc.py#L266) to get the 3D bounding box annotations -- set **pts** to the 8 bounding box corners (see file models_info.json provided with the BOP datasets), and **R** and **t** to the GT object pose.
