### ISSUE TITLE
Error in opening the .ply files in the "models_eval" directory.

### ISSUE THREAD

**Issue by AlbertLZG** [thodan/bop_toolkit#15]
It seems that the .ply files in the "models_eval" directory are broken. The content is wrong no matter during loading them in python or opening them in editors.

**Comment by AlbertLZG** [comment]
And the .ply files in the "models" are fine.

**Comment by bertid** [comment]
@AlbertLZG in which dataset does this happen?

**Comment by AlbertLZG** [comment]
Sorry for so late reply, I test the files in lm_bop dataset previously.
I find the problem is that these files are memmap and cannot be loaded as text files.
Now, I have solve this problem, thank you~

**Comment by AlbertLZG** [comment]
Sorry for so late reply, I test the files in lm_bop dataset previously.
I find the problem is that these files are memmap and cannot be loaded as text files.
Now, I have solve this problem, thank you~ @bertid
