### ISSUE TITLE
Problem with extraction of train_real data from the archive on Huggingface

### ISSUE THREAD

**Issue by kirilllzaitsev** [thodan/bop_toolkit#151]
Hi, I have downloaded the YCB-V dataset from Huggingface without visible issues:
![image](https://github.com/user-attachments/assets/bb6cc7b8-0f01-4cff-8bdc-d7a276e88f69)

However, trying to extract the contents of `ycbv_train_real.zip`, I receive a plenty of errors indicating some corruption of the archive:
```
file #52409:  bad zipfile offset (local header sig):  3402047327
file #52410:  bad zipfile offset (local header sig):  3402047892
file #52411:  bad zipfile offset (local header sig):  3402048470
file #52412:  bad zipfile offset (local header sig):  3402049135
file #52413:  bad zipfile offset (local header sig):  3402050067
file #52414:  bad zipfile offset (local header sig):  3402051181
file #52415:  bad zipfile offset (local header sig):  3402634224
file #52416:  bad zipfile offset (local header sig):  3402730315
file #52417:  bad zipfile offset (local header sig):  3402730781
file #52418:  bad zipfile offset (local header sig):  3402731264
file #52419:  bad zipfile offset (local header sig):  3402731861
file #52420:  bad zipfile offset (local header sig):  3402732457
file #52421:  bad zipfile offset (local header sig):  3402733027
file #52422:  bad zipfile offset (local header sig):  3402733657
file #52423:  bad zipfile offset (local header sig):  3402734621
file #52424:  bad zipfile offset (local header sig):  3402735732
file #52425:  bad zipfile offset (local header sig):  3403318313
file #52426:  bad zipfile offset (local header sig):  3403415271
```
Unarchiving results in an almost empty `train_real` folder. Attempting to fix it with `zip -FF` command doesn't work.

Could you help with downloading the real training images from the BOP version of YCB-V?

**Comment by nv-nguyen** [comment]
Hi @kirilllzaitsev,

HuggingFace only hosts files <= 50GB, `ycbv_train_real.zip`> 70GB so we have to split `ycbv_train_real.zip` into `ycbv_train_real.zip` and `ycbv_train_real.z01`. Please see [YCB-V section in BOP dataset page](https://bop.felk.cvut.cz/datasets/).

Therefore, both files must be downloaded before they can be unzipped. Please run the following commands:
```
wget https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/ycbv/ycbv_train_real.zip
wget https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/ycbv/ycbv_train_real.z01
zip -s0 ycbv_train_real.zip --out ycbv_train_real_all.zip
unzip ycbv_train_real_all.zip
```

I've just tried the commands above and it works fine. Please feel free to re-open the issue if it is not working.

**Comment by kirilllzaitsev** [comment]
@nv-nguyen, thank you. My `snapshot_download` call didn't account for the fact that `ycbv_train_real.z01` doesn't end with `*zip`, skipping it when downloading the other archives
