### ISSUE TITLE
Why the objects in testing are much smaller than that in training set

### ISSUE THREAD

**Issue by shuluoshu** [thodan/bop_toolkit#16]
Hi , @thodan @bertid
       I am not familiar with the rendering of OpenGL, and I just combine the separated given training images onto a background image, however, the objects in combined image are much larger than that in your test image.  (How to put them in different depth?  ) . What's wrong? 

 Thanks so much!

**Comment by thodan** [comment]
Hi shuluoshu. When rendering using function [render_object(self, obj_id, R, t, fx, fy, cx, cy)](https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/renderer.py#L62), you control the depth of the object via the translation vector **t**, which expresses the location of the object center in the camera coordinate system. Maybe your translation vector has wrong units? How do you render?
