### ISSUE TITLE
Visualization Scripts for 2D tasks (detection and segmentation)

### ISSUE THREAD

**Issue by SajjadPSavoji** [thodan/bop_toolkit#161]
Hey folks! I am wondering if there is a vis script for estimated/gt 2D annotations in this toolkit. So far I have not been able to find it. There is a script to visualize estimated and gt poses, but they are not useful for the 2D tasks.

**Comment by MartinSmeyer** [comment]
Hi!

Not directly from the gt_info, but there is draw_rect() which simply draws a 2D box on an image.

https://github.com/thodan/bop_toolkit/blob/7309afe2425d10b2d349652ec569eec433671b05/bop_toolkit_lib/visualization.py#L30
