### ISSUE TITLE
 'FreeTypeFont' object has no attribute 'getsize' 

### ISSUE THREAD

**Issue by SajjadPSavoji** [thodan/bop_toolkit#162]
when running `scripts/vis_est_poses.py` with pillow >= 10 you will get an error saying that font object has not attribute `getsize`. Fix the requirement file to specify the exact pillow version that works with the source code. 
 
The work around "pip install pillow==9.5.0".

**Comment by MartinSmeyer** [comment]
Thank you, limited the version range.
