### ISSUE TITLE
Why to convert depth to distance in evaluation?

### ISSUE THREAD

**Issue by zeal-github** [thodan/bop_toolkit#19]
Hi, I am curious about the conversion from depth to distance when evaluation. I think with the depth map, we can do the same operation when we calculate Evsd.  Nor in the original paper or this challenge explain why using distance to calculate difference is better.
Thanks！

**Comment by thodan** [comment]
Hello. Imagine two patches, one on the left side of an image and one on the right side, both showing the same object from the same view (i.e. the patches in RGB are identical up to perspective distortion). The depth map stores at each pixel the Z coordinate and has different values in the left and the right patch. To treat both patches in the same way, we convert the depth map to the distance map (storing at each pixel the distance from the camera center to the closest surface) which have the same values in both patches.
