### ISSUE TITLE
Can this tool make lineMod like dataset with my own data?

### ISSUE THREAD

**Issue by YanqingWu** [thodan/bop_toolkit#22]
I can not understand how the tool works, the docs contains few information.

I want to get the Ground-truth annotations as blew:
cam_R_m2c - 3x3 rotation matrix R_m2c (saved row-wise).
cam_t_m2c - 3x1 translation vector t_m2c.

**Comment by thodan** [comment]
For the existing datasets, the GT annotations are provided in the archives which can be downloaded from here: https://bop.felk.cvut.cz/datasets/. If you want to capture new images and annotate them with 6D GT poses, you can consult the T-LESS paper: http://cmp.felk.cvut.cz/~hodanto2/data/hodan2017tless.pdf
