### ISSUE TITLE
Multiprocess rendering

### ISSUE THREAD

**Issue by zeal-github** [thodan/bop_toolkit#23]
Hi, I want to know that how can I render image multiprocessing.
I create one renderer(python)  instance, and add objects to this renderer. I want to call it's render_object method multiprocessly. I implement this in my dataset loader. However it do not worked or dump any error.
Can you give me some advices?
Thanks!

**Comment by thodan** [comment]
Hello, the render_object function has not been tested with multithreading/multiprocessing and I assume it is not thread-safe. Or have you managed to make it work?
