### ISSUE TITLE
meshlab in ubuntu

### ISSUE THREAD

**Issue by pyni** [thodan/bop_toolkit#26]
Hi,when i try remesh_models_for_eval.py,  i wonder how to set path of Meshlab in Ubuntu.

I set the path into '/usr/bin/meshlab ', but it shows:
![image](https://user-images.githubusercontent.com/18031767/70524160-8d154780-1b7f-11ea-8691-81bcf5463058.png)

**Comment by MartinSmeyer** [comment]
Hi @pyni,
please set the path to meshlabserver, i.e.
/usr/bin/meshlabserver
