### ISSUE TITLE
YCB-V Ground Truth Transformation Cannot Achieve Full Score?

### ISSUE THREAD

**Issue by georgegu1997** [thodan/bop_toolkit#27]
I am doing a sanity check by feeding ground truth transformation of the YCB-V dataset into the evaluation script, but it cannot achieve full `bop19_average_recall_mspd` and `bop19_average_recall_mssd` on both Github code and BOP online system (unpublished entry name: "Ground-Truth-Test_Only/YCB-V/test"). And `bop19_average_recall_vsd` is 1.

More specifically, only the objects with id 13 and 18 have the problem. Object with id 13 keeps getting score 0 in all threshold settings and the score of object id 18 varies with thresholds. Scores for all other objects are 1. 

The csv file I used is attached, and I manually compared some of it with `scene_gt.json` and it should be good. Could you please help see where I mess it up? Thanks! 
[gt_ycbv-test.zip](https://github.com/thodan/bop_toolkit/files/4007524/gt_ycbv-test.zip)

**Comment by Dangzheng** [comment]
@georgegu1997 Hi, I'm wondering if you fixed the bug or have any progress. I run the same test and noticed the same error when using mssd. The recall for object 13 is zero. I was using ground-truth, but the error of the object 13 is huge.

![image](https://user-images.githubusercontent.com/13902867/72962975-dc8e9a80-3df0-11ea-92d7-e11bedc61f73.png)
![image](https://user-images.githubusercontent.com/13902867/72963094-427b2200-3df1-11ea-8d97-13908e1fd6b2.png)

**Comment by thodan** [comment]
Hi, thanks @georgegu1997 for pointing out this issue. We are currently looking into this and have found the bug. We are doing some more tests and will provide an explanation & a bug fix soon.

**Comment by thodan** [comment]
The issue has been resolved and the submissions to the BOP Challenge 2019 re-evaluated. You can find more details [here](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_challenge_2019_re-evaluation_27-01-2020.md).
