### ISSUE TITLE
All scene ground truths are set to True if using visib_gt_min = 0.1

### ISSUE THREAD

**Issue by mehtakhil** [thodan/bop_toolkit#28]
In the recent commit 975fcf25cb77529a92176cbffc4a4b87ad6d0e20 where 'visib_gt_min' was changed to -1, the code in eval_calc_scores.py was changed where the valid ground truth scenes are assigned True/False based on scene_targets.

In eval_calc_scores.py.
```  
      216. scene_gt_valid[im_id] = [True] * len(im_gt)
      217. if p['visib_gt_min'] >= 0:
      218.  # All GT poses visible from at least 100 * p['visib_gt_min'] percent
      219.  # are considered valid.
      220.  for gt_id, gt in enumerate(im_gt):
      221.    is_target = gt['obj_id'] in im_targets.keys()
      222.    is_visib = im_gt_info[gt_id]['visib_fract'] >= p['visib_gt_min']
      223.    scene_gt_valid[im_id].append(is_target and is_visib)

```
Now, all the ground truths are considered valid as the append doesn't affect when considering scene_gt_valid[:im_gt] for further evaluation.

Because of the addition of line 216, line 223 might have to be changed to 
```
scene_gt_valid[im_id][gt_id] = is_target and is_visib
```

**Comment by thodan** [comment]
Thanks for pointing this out! The bug has been fixed in the [latest commit](https://github.com/thodan/bop_toolkit/commit/2f9469f79f79207b9a06ae203cc67c9332bf4495).

Note that this bug did not influence the scores in the BOP Challenge 2019 or scores reported in the BOP ECCV'18 paper.
