### ISSUE TITLE
AttributeError: 'list' object has no attribute 'flatten' when rendering RGBD data

### ISSUE THREAD

**Issue by ZiqiChai** [thodan/bop_toolkit#29]
When I set up `config.py` and prepare lm dataset already.
I got the following error when run `render_train_imgs.py` to get RGB-D images.

**********************************************************************************************************
Traceback (most recent call last):
  File "render_train_imgs.py", line 226, in <module>
    out_path=out_path, obj_id=obj_id), scene_camera)
  File "/home/ziqi/bop_toolkit/bop_toolkit_lib/inout.py", line 175, in save_scene_camera
    im_camera['cam_K'] = im_camera['cam_K'].flatten().tolist()
AttributeError: 'list' object has no attribute 'flatten'
**********************************************************************************************************

After looking deeper into the code, I see scene_camera has `.flatten().tolist()` method and `inout.py` also has `.flatten().tolist()` method in `save_scene_camera(path, scene_camera)` function.

**********************************************************************************************************
codes in `render_train_imgs.py`:
```
scene_camera[im_id] = {
  'cam_K': dp_camera['K'].flatten().tolist(),
  'depth_scale': dp_camera['depth_scale'],
  'view_level': int(views_level[view_id])
}
```
codes in `inout.py`:
```
if 'cam_K' in im_camera.keys():
  im_camera['cam_K'] = im_camera['cam_K'].flatten().tolist()
```
**********************************************************************************************************

I fixed this error by remove all `.flatten().tolist()` in `render_train_imgs.py` to make sure it's not converted to list before `save_scene_camera()` function.
I want to know is it OK to do like this?  Or, the code itself is right while I missed something?

**Comment by thodan** [comment]
Thanks for pointing this out. This issue is fixed on the latest commit: https://github.com/thodan/bop_toolkit/commit/88429c8cdce64a832b4389346b5748ec237aa457
