### ISSUE TITLE
Does bop_toolkit have an example that converts from depth to point cloud?

### ISSUE THREAD

**Issue by TouchDeeper** [thodan/bop_toolkit#34]
Hello, 

As the title said, Does bop_toolkit have an example that converts from depth to point cloud?

**Comment by thodan** [comment]
The SIXD Toolkit (which is the predecessor of the BOP Toolkit) contains such function (rgbd_to_point_cloud): https://github.com/thodan/sixd_toolkit/blob/9430a1970d1ee48abd2d2ff7eceee50b2782a7a8/pysixd/misc.py#L64
