### ISSUE TITLE
Is the SiSo task suitable for Bop challenge?

### ISSUE THREAD

**Issue by TouchDeeper** [thodan/bop_toolkit#35]
Hello,

My method focuses on pose registration of object pose estimation, object segmentation is not yet developed. Now we can solve the SiSo problem, Is the SiSo task suitable for Bop challenge? Thanks a lot!

**Comment by thodan** [comment]
Hello, the BOP Challenge (bop.felk.cvut.cz) is focused on the ViVo task (i.e. a generalization of the SiSo task). The ECCV'18 paper (http://cmp.felk.cvut.cz/~hodanto2/data/hodan2018bop.pdf) considers the SiSo task and you can compare your method to the methods in the paper.

**Comment by TouchDeeper** [comment]
I want to ask further whether the input of ECCV'18 paper is the depth contained in mask_visib or just the mask.

**Comment by TouchDeeper** [comment]
@thodan I didn't develop the object identifiers. My method requires the point cloud of the instance (what the mask can do) and the object to which the instance belongs. Could you please provide some advice on how to use your bop toolkit to evaluate my method?

**Comment by thodan** [comment]
@TouchDeeper, you can prepare your 6D pose estimates in the BOP Challenge format (https://bop.felk.cvut.cz/challenges/bop-challenge-2020/#howtoparticipate) and submit to the BOP evaluation system. To get the masks at test time, you may use e.g. Mask R-CNN.
