### ISSUE TITLE
Store coco RLE format masks into json files instead of binary mask images to reduce the bop dataset size?

### ISSUE THREAD

**Issue by hiyyg** [thodan/bop_toolkit#38]
Like coco annotations, the masks can be stored in RLE format in `scene_gt_info.json` files, so that the dataset size can be largely reduced.

**Comment by thodan** [comment]
@hiyyg, the [latest pull request](https://github.com/thodan/bop_toolkit/pull/39) from @MartinSmeyer includes a converter from BOP format to COCO format, where masks are saved in RLE format.
