### ISSUE TITLE
Where can I download the file 'test_targets_bop19.json' ?

### ISSUE THREAD

**Issue by GodZarathustra** [thodan/bop_toolkit#40]
Hi, Hodan:
the test targets file '**test_targets_bop19.json**' needs to be saved under the bop dataset folder, but I didn't find this file in https://bop.felk.cvut.cz/datasets/, where can I download it?（especially for tless）
if it's not public, could you tell me the data formate of this file so I can evaluate my method on your metric?

**Comment by thodan** [comment]
Hello, the test_targets_bop19.json files are in the base archivers. For T-LESS: http://ptak.felk.cvut.cz/6DB/public/bop_datasets/tless_base.zip

**Comment by jrryzh** [comment]
Hi,thodan
the link you gave above is not available for a few days now, can you contact me by email, i really need the json for testing
my email is 1393769743@qq.com. Thanks so much!

**Comment by thodan** [comment]
@jrryzh You can find updated links at: https://bop.felk.cvut.cz/datasets/
