### ISSUE TITLE
KeyError: 'total_recall' in show_performance_bop19.py

### ISSUE THREAD

**Issue by WilliamKRobert** [thodan/bop_toolkit#41]
It looks like in, for example, ```error=vsd_ntop=-1_delta=15.000_tau=0.050/matches_th=0.050_min-visib=-1.000.json```, there is no key named ```total_recall```. I run the script by simply typing: ```python scripts/show_performance_bop19.py``` Am I missing something?

**Comment by thodan** [comment]
The key should be 'recall' instead of 'total_recall' (on lines 175 and 176). This has been fixed in the latest commit.
