### ISSUE TITLE
How to generate train image?

### ISSUE THREAD

**Issue by gachiemchiep** [thodan/bop_toolkit#42]
Hello.
I run the scripts/render_train_imgs.py. But unfortunately, the output is not as similar as training image in lm/train_pbr dataset.

Output of the script: 
![000000](https://user-images.githubusercontent.com/2300329/94125668-9ca51900-fe91-11ea-8cae-b461d1a304a4.png)

Training file inside lm/train_pbr
![000003](https://user-images.githubusercontent.com/2300329/94125865-e2fa7800-fe91-11ea-9e98-fd378250c03e.jpg)

Is there any script that needed to merge output of render_train_imgs.py into above file?

**Comment by MartinSmeyer** [comment]
The training images are generated with another software called BlenderProc. Have a look here to replicate/adapt the data:
https://github.com/DLR-RM/BlenderProc/tree/master/examples/bop_challenge

If you want to understand in general how the BlenderProc config works, you should also look at the other examples starting from here:
https://github.com/DLR-RM/BlenderProc/tree/master/examples/basic
