### ISSUE TITLE
 b'The GLFW library is not initialized'

### ISSUE THREAD

**Issue by ldepn** [thodan/bop_toolkit#43]
when i run render_python , i have the error " b'The GLFW library is not initialized'

**Comment by chrisxu1995** [comment]
I also met the error, when I run calc_gt_info.py. Have you solved the Issue?

**Comment by thodan** [comment]
If this is blocking you, please try to use a different backend for glumpy: https://github.com/thodan/bop_toolkit/blob/529f11135315cffd536d7b5ea44bcf326daa9a6a/bop_toolkit_lib/renderer_py.py#L20
