### ISSUE TITLE
No module named 'bop_toolkit_lib ?

### ISSUE THREAD

**Issue by Abduoit** [thodan/bop_toolkit#44]
Hi
I am trying to follow the steps [here](https://github.com/thodan/bop_toolkit#usage)

when I run  `python scripts/eval_bop19.py  --result_filenames=gt-equivalent_ycbv-test.csv`

I get this error
```
    from bop_toolkit_lib import config
ModuleNotFoundError: No module named 'bop_toolkit_lib'
```

**Comment by thodan** [comment]
Please try to append the path to bop_toolkit to the PYTHONPATH environmental variable. In bash, you can do this by:

export PYTHONPATH="${PYTHONPATH}:/your/path/to/bop_toolkit"
