### ISSUE TITLE
Where to buy real objects for bop datasets ? 

### ISSUE THREAD

**Issue by gachiemchiep** [thodan/bop_toolkit#45]
Hello. 
I think this question is totally unrelated, but does anyone know where to buy or how to make those objects in bop datasets? 
We want to use models trained by bop on a real-robot with gripper for bin picking and other stuff. 

Thank you.

**Comment by thodan** [comment]
Hello. The easiest to get are probably the YCB objects. Click on "Order YCB Object Set" on this website: https://www.ycbbenchmarks.com/object-set/

**Comment by gachiemchiep** [comment]
@thodan Thanks
