### ISSUE TITLE
Saving estimated poses - link of format description is not working

### ISSUE THREAD

**Issue by Timon-Hoefer** [thodan/bop_toolkit#47]
Hi there,
the link given in:

"""
Usage
2. Run your method.
"format description" 
"""

throws "Server Error (500)".

Could you fix that, or give a short explanation on how the format of the output should look like to be evaluated with the bop_toolkit?

Best regards
Timon

**Comment by thodan** [comment]
Hi Timon, thanks for pointing this out. The link is fixed now.
