### ISSUE TITLE
Create models_info.json for own models

### ISSUE THREAD

**Issue by Timon-Hoefer** [thodan/bop_toolkit#48]
Hi there,

I want to evaluate pose errors with my own obj. models. Therefore I need to create the models_info.json.
Have you any guide on how to create this file? It looks like you were using MeshLab for this task. But I am not sure.

Best wishes
Timon

**Comment by thodan** [comment]
Hi Timon, you can use this script to create the models_info.json file: https://github.com/thodan/bop_toolkit/blob/master/scripts/calc_model_info.py

**Comment by Timon-Hoefer** [comment]
You are the best! Thanks Thodan.

**Comment by maedhril** [comment]
Hi There,

I am also trying to use my own models and I used the script you shared. However, I also noticed some property called "symmetry_discrete" that I do not know what it means. Do you know what it is or how can I generate this information for my own model?
