### ISSUE TITLE
I have an visual error in mask images

### ISSUE THREAD

**Issue by lu-ming-lei** [thodan/bop_toolkit#49]
![2b43c52b59b551f812c2696798ef770](https://user-images.githubusercontent.com/55871206/99907202-62aa9480-2cd3-11eb-822b-3856052c280e.png)
![f528f7c88353c78367b22441eb21925](https://user-images.githubusercontent.com/55871206/99907207-676f4880-2cd3-11eb-9309-285fbb6d196b.png)
For example in YCBV--0091video--899picture, some of the hidden points of banana are shown in the mask image.
I download YCBV dataset from the website of boptookit and wonder which block did I deal with that went wrong.

**Comment by thodan** [comment]
Hello. The mask of the visible object part is calculated using the depth image channel and may be not pixel-perfect if the depth channel suffers from noise. Please refer to [bop_toolkit_lib/visibility.py](https://github.com/thodan/bop_toolkit/blob/master/bop_toolkit_lib/visibility.py) to see how the visibility mask is calculated.
