### ISSUE TITLE
Symmetry information in model_info.json ?

### ISSUE THREAD

**Issue by maedhril** [thodan/bop_toolkit#50]
I am trying to use my own models and I used 'calc_model_info.json' script. However, The script does not generate some property called "symmetry_discrete" that I do not know what it means. Do you know what it is or how can I generate this information for my own model?

#48

**Comment by bertid** [comment]
This field contains a list of 3D poses (each represented as 4x4 matrix) under which your model is symmetric. The identity pose is omitted. In other words, if the model is transformed by one of the listed poses, it does not change (too much).

For example, a cereal box would have three poses in that list, if texture is ignored (flip over the long side, flip over the short side, flip over long and short side).

**Comment by maedhril** [comment]
How about more complex objects that have symmetry transformation beyond simple axis flips. For example; in YCB-V dataset there are some objects that have symmetry transformation as following;

```
    "symmetries_discrete": [
      [0.00179515,
      -0.999956,
      -0.00918835,
      -0.451143,
      0.99999,
      0.00175811,
      0.00403816,
      -0.140551,
      -0.00402183,
      -0.00919551,
      0.99995,
      -0.00311599,
      0,
      0,
      0,
      1],
```
I mean this matrix must be calculated from a script or library but I did not have any luck finding any library or method to calculate these values.

**Comment by bertid** [comment]
@maedhril Right, there is a script but it is unfortunately not released. It is a semi-manual process, where you first define the symmetry class of the object (there aren't that many, usually boxes, n-fold rotations around an axis which is usually the z-axis etc.), and then ICP is used to further improve those initial poses.

If your models are manually created CAD models and the coordinate frame is nicely aligned (center in the object center, axis aligned with whatever symmetry you have), you can also often come up with the poses yourself. If the models are the result of some scanning this is more difficult.

The scripts are not really a secret and I can send them to you, but they are undocumented and require a license for the HALCON library. Free licenses are available for universities, but there is a steep initial learning curve. Alternatively, if you just have a few objects you can send them to me and I can annotate them and send you back the symmetries. Be advised that you might have to filter those symmetries to account for texture. The script only takes geometry into account, and depending on what you want to measure you might want to remove some symmetries for which the texture changes drastically. That is highly domain dependent, though,

**Comment by maedhril** [comment]
@bertid If you can send me the scripts that would be fantastic because besides the objects currently I have, I will probably try new objects in the future. Besides, I think looking at the script will be helpful whether I will try to create my own script or I will try to integrate HALCON. So if you can send me the script to my mail account cptmaa@gmail.com; I would be very thankful.

**Comment by bertid** [comment]
@maedhril Sure - I'll clean up the scripts a bit and send them to you in the next days.

**Comment by HamilkarBrq** [comment]
Hey @bertid,
I am facing similar problems like @maedhril described at the moment as well. Could you send me the script to my university mail account j.schons@wzl.rwth-aachen.de ?
Thanks in advance.

**Comment by bertid** [comment]
@maedhril @HamilkarBrq The mail is on its way - let me know if you have any issues with the scripts (which is quite likely, they really are spaghetti code, no need to comment because I will run this one time only scripts).

**Comment by YyYyYong0331** [comment]
Hey @bertid,
I am facing similar problems, too. Could you send me the script?
The mail account: wyong233@gmail.com
Thanks

**Comment by bertid** [comment]
@YyYyYong0331 The mail is on its way.

**Comment by baichuan05** [comment]
Hey @bertid,
I am facing similar problems, too. Could you send me the script?
We are trying to extend ycbv to a larger one with other ycb objects.
The mail account: baichuan.huang@rutgers.edu
Thanks

**Comment by CQUChenC** [comment]
> Hi [@baichuan05](https://github.com/baichuan05) - apologies for the delay.嗨 - 很抱歉耽搁了。
> 
> Attached are the HALCON scripts that were used to build the symmetries for the BOP objects.附件是用于为 BOP 对象构建对称性的 HALCON 脚本。
> 
> Please note again that they are not very polished. The idea is to first run script [#1](https://github.com/thodan/bop_toolkit/pull/1), where you can use sort of a GUI to set the object symmetries. Different types are available (box, n-fold symmetry etc.). They usually work out of the box if (1) the model’s symmetry axis is the z-axis and (2) the center of the coordinate frame is also the center of symmetry. If that is not the case, you will have to manually adjust those values in the code for your object.请再次注意，它们不是很抛光。这个想法是首先运行 script [#1](https://github.com/thodan/bop_toolkit/pull/1) ，您可以在其中使用某种 GUI 来设置对象对称性。有不同的类型可供选择（盒形、n 折对称等）。如果 （1） 模型的对称轴是 z 轴，并且 （2） 坐标系的中心也是对称中心，则它们通常是开箱即用的。如果不是这种情况，则必须在对象的代码中手动调整这些值。
> 
> Script [#2](https://github.com/thodan/bop_toolkit/issues/2) will take all the symmetries and produce the json file.脚本 [#2](https://github.com/thodan/bop_toolkit/issues/2) 将获取所有对称性并生成 json 文件。
> 
> I’m quite sure that they will not run out of the box for you, so please just let me know if you run into any issues or need a quick walkthrough. In any case, you can produce the symmetries with any program of your choice, or even manually in some cases if the model is well behaved.我很确定它们不会开箱即用，所以如果您遇到任何问题或需要快速演练，请告诉我。在任何情况下，您都可以使用您选择的任何程序生成对称性，如果模型表现良好，甚至可以在某些情况下手动生成对称性。
> 
> [bop_symmetries.zip](https://github.com/thodan/bop_toolkit/files/7031040/bop_symmetries.zip)

Thank you for providing the code to compute symmetry axes. I attempted to calculate symmetry axes for my own model, but encountered an issue where the path "DictFile:=PathToDatasets + results.hdict" specified on line 24 does not exist, preventing the program from running properly. Could you advise where this file should be configured?

![Image](https://github.com/user-attachments/assets/00e69507-902a-441d-aadc-7ae453b3f5f3)
