### ISSUE TITLE
vis_est_poses.py runs into various errors

### ISSUE THREAD

**Issue by HamilkarBrq** [thodan/bop_toolkit#51]
Ahoj,
I was trying to run the vis_est_poses.py script on the created  [.csv file](https://github.com/thodan/bop_toolkit/files/5874777/pix2pose-iccv19_tless-test-primesense.zip) by Pix2Pose on the T-Less dataset, but ran into different errors after running the script several times. 

- `corrupted size vs. prev_size`
- `munmap_chunk() invalid pointer`
- `free(): invalid size`
all resulting in `Aborted (core dumped)`

Google search suggests that they're C/C++ related, so I'm a little lost rn.
Any help is greatly appreciated.
Cheers,
Jan

**Comment by thodan** [comment]
Please try setting 'renderer_type': 'python' (https://github.com/thodan/bop_toolkit/blob/master/scripts/vis_est_poses.py#L44). The errors may be coming from the BOP renderer which is written in C++ and may have been incorrectly compiled.
