### ISSUE TITLE
How to get the new targets files?

### ISSUE THREAD

**Issue by Xiaflowers** [thodan/bop_toolkit#57]
Hello, thodan！

I've trained my own dataset. But I found that evaluating datasets requires  targets files.
I downloaded the test_targets_bop19.json file, but I'm sorry it doesn't meet my needs.
So can you tell me how to get my own targets files? Or is there a script to generate this file?

It would be great if you could tell me the method！Anyway, thank you for such a good project！

**Comment by thodan** [comment]
Hello, there is no script for creating the JSON file with targets. But the format of the file is quite simple, so it shouldn't be difficult to create the file by yourself. You can use files `scene_gt.json` and `scene_gt_info.json` to collect info about object instances present in the images.

**Comment by Xiaflowers** [comment]
Oh! Thank you for your reply!
So anather question is what the 'inst_count' mean?

**Comment by thodan** [comment]
'inst_count' is the number of instances of an object that are present in the image.

**Comment by hannes56a** [comment]
@Xiaflowers : Hi, did you solve your problem. I have currently the same problem: I need such a target file to evaluate my own dataset. Perhabs you wrote a script which you would like to share? That would help me :-)

**Comment by thodan** [comment]
Hello, attached is a script which creates a target file (considering all GT poses in which the object is visible from at least 10%).

[enumerate_test_targets.zip](https://github.com/thodan/bop_toolkit/files/7802327/enumerate_test_targets.zip)

**Comment by hoenigpeter** [comment]
> Hello, attached is a script which creates a target file (considering all GT poses in which the object is visible from at least 10%).
> 
> [enumerate_test_targets.zip](https://github.com/thodan/bop_toolkit/files/7802327/enumerate_test_targets.zip)

Hi! Could you include this very helpful script in the repo in the scripts folder? Would be really helpful!
