### ISSUE TITLE
3D annotation tool contribution

### ISSUE THREAD

**Issue by AnasIbrahim** [thodan/bop_toolkit#65]
Hi,

I wrote this annotation tool to manually annotate real scenes. The tool uses the BOP format and generates "scene_gt.json" file. Then the rest of the toolkit is used to generate the other annotations. It would be possible to contribute it to the toolkit. 

https://github.com/FLW-TUDO/3d_annotation_tool

Here is a quick video to show how it works.

https://youtu.be/hIaOqvyR9v0

**Comment by thodan** [comment]
Hello! This tool looks great and we would be happy to include it into the BOP toolkit. Could you create a pull request? We can discuss details there. Thanks!
