### ISSUE TITLE
Questions about cropping the PBR images

### ISSUE THREAD

**Issue by JZhao12** [thodan/bop_toolkit#67]
Hi,

Sorry to disturb you, I'm currently using PBR images for my experiments, and I met a small problem when I tried to crop the object from the image. I list an example ground truth annotation blow, for example this one, the first element of "bbox_obj" is -40. But when I used this '-40' as the bounding box value, it did not crop the image. 

Example ground truth:
"bbox_obj": [-40, 148, 149, 96], "bbox_visib": [0, 158, 97, 84], "px_count_all": 8562, "px_count_valid": 6883, "px_count_visib": 4060, "visib_fract": 0.47418827376781125}

Example crop code:
ROI = image[bbox_obj[1]:bbox_obj[1]+bbox_obj[3], bbox_obj[0]:bbox_obj[0]+bbox_obj[2]]

Could you please help me with this issue? Thank you very much!
Jianyu

**Comment by MartinSmeyer** [comment]
Hi @JZhao12 

You mixed up the order, bbox is in the format x,y,w,h not y,x,h,w

"bbox_obj" refers to the bounding box that encompasses the full object no matter if it is occluded or outside the actual image. "bbox_visib" gives you the bounding box of only the visible part of the object inside the image. Therefore x is at 0, while for  "bbox_obj" x is at -40.

If you really want to use "bbox_obj" you need to make sure that the bounding box is inside your image, i.e.

```
x,y,w,h = bbox_obj

left_trunc = np.maximum(x, 0)
right_trunc = np.minimum(x+w, image.shape[1])
top_trunc = np.maximum(y, 0)
bottom_trunc = np.minimum(y+h, image.shape[0])

ROI = image[left_trunc:right_trunc, top_trunc:bottom_trunc]
```

**Comment by JZhao12** [comment]
Thank you so much for your reply! It really really helps! @MartinSmeyer

**Comment by MartinSmeyer** [comment]
No problem, there was still a type in my answer, check the update.
