### ISSUE TITLE
How to compute split params for a custom dataset 

### ISSUE THREAD

**Issue by jrabary** [thodan/bop_toolkit#69]
We have generated a synthetic dataset with blenderproc and like to use it for evaluation using bop toolkit.

Since blenderproc don't generate the `scene_gt_info.json` file we tried to generate it with the script `calc_gt_info.py`.

But this script need some additional data in order to work (depth range, azimuth_range, élèves_range):

```
 # Linemod (LM).
  if dataset_name == 'lm':
    p['scene_ids'] = list(range(1, 16))
    p['im_size'] = (640, 480)

    if split == 'test':
      p['depth_range'] = (600.90, 1102.35)
      p['azimuth_range'] = (0, 2 * math.pi)
      p['elev_range'] = (0, 0.5 * math.pi)
```

How to compute these values for a custom dataset generated with blenderproc ?

**Comment by MartinSmeyer** [comment]
These parameters can be just read from the BlenderProc config/python file, i.e. azimuth is typically not constrained (`p['azimuth_range'] = (0, 2 * math.pi)`) and `elev_range` is often `p['elev_range'] = (0, 0.5 * math.pi)` The depth range can be approximated from the camera sampler shell radius. In the end these parameters are not relevant for the evaluation.
