### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by CaffeMrDe** [thodan/bop_toolkit#7]
If I has a 3D model about ply file,  how can I train my dataset?
There are no application doc about using train rendering code.

Thanks!

**Comment by thodan** [comment]
Generation of the training images is up to every participant (it is considered to be a part of the method -- there are many ways how to generate the training images). We provide only a simple renderer that renders the object models against a black background (which is likely not sufficient to train CNN-based methods but can be used as a base for a more complex renderer). Please consult e.g. the literature below.

[1] Kehl et al., SSD-6D: Making RGB-based 3D detection and 6D pose estimation great again
[2] Hodan et al., Photorealistic Image Synthesis for Object Instance Detection
