### ISSUE TITLE
Unable to create more than one vispy renderer because of singleton

### ISSUE THREAD

**Issue by Usaali** [thodan/bop_toolkit#74]
Hi, I was trying to get the render_train_imgs.py script to run and encountered a problem. I am not sure if its related to my python version or to the vispy renderer implementation, as i never worked with singletons before.

When creating a second renderer, for example a depth renderer after having an rgb renderer already, the singleton function returns the first renderer object instead of creating a second renderer. This means that the call to renderer.create_renderer returns fine but instead of having a depth renderer, it is the same rgb renderer object created by the previous call. 
![image](https://user-images.githubusercontent.com/65233682/177864460-d077e800-9261-4408-a88e-5e2144477093.png)

For now i fixed it by adding the object to the instances dictionary in the singleton function with the mode instead of the class as a key, but this is more of a hotfix than an actual clean solution.
![image](https://user-images.githubusercontent.com/65233682/177864747-ce55c7fe-20f7-4539-8758-2721931ef9b9.png)

**Comment by MartinSmeyer** [comment]
Should be solved now by #82
