### ISSUE TITLE
Fail to download the dataset

### ISSUE THREAD

**Issue by thomastangucb** [thodan/bop_toolkit#75]
Hello, it seems the dataset server (https://bop.felk.cvut.cz/) is down: 

> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Any other source to download the data? Thanks.

**Comment by MartinSmeyer** [comment]
The website is up again :)

**Comment by 63445538** [comment]
Hi,

The source of datasets cannot be accessed due to 403 Forbidden. Could you please have a check again?

Best,
Rui

**Comment by MartinSmeyer** [comment]
I can access them, which one specifically?

**Comment by 63445538** [comment]
> I can access them, which one specifically?

This link: https://bop.felk.cvut.cz/media/data/bop_datasets/

![image](https://user-images.githubusercontent.com/16507095/178693530-80bc4260-d258-44c3-adea-0ec3f4b07046.png)

**Comment by MartinSmeyer** [comment]
You can download the datasets here:
https://bop.felk.cvut.cz/datasets/

**Comment by 63445538** [comment]
> You can download the datasets here: https://bop.felk.cvut.cz/datasets/

The dataset can be downloaded via the website, thank you so much.

Best,
Rui
