### ISSUE TITLE
403 forbiden when trying to see results example

### ISSUE THREAD

**Issue by hansaskov** [thodan/bop_toolkit#78]
Hi, i'm trying to understand how the results csv is formatted. 

The Readme mentions an example, but when i click the link, i receive a

403 Forbidden response.  

Here is the link: https://bop.felk.cvut.cz/media/data/bop_sample_results/

**Comment by thodan** [comment]
Hello @hansaskov, here is a correct link: https://bop.felk.cvut.cz/media/data/bop_sample_results/bop_challenge_2019_sample_results.zip

I've also fixed it in the README.md file.
