### ISSUE TITLE
ValueError: Only triangular faces are supported.

### ISSUE THREAD

**Issue by zhhiyuan** [thodan/bop_toolkit#80]
I want to use calc_gt_masks.py to generate masks for the custom data.  When loading the object model, it read the ply data using inout.load_ply function, however showing ValueError: Only triangular faces are supported.
Can you give me some advice on converting my ply model to the triangular faces ply model?

**Comment by zhhiyuan** [comment]
Problem solved! I annotated the raise triangular error code. By using this simple method, I get the mask I wanted.

**Comment by MoTahoun** [comment]
Hi @zhhiyuan 

Could you please tell me the steps or the modifications that you have done to the code that solve your issue as I am facing the same error "ValueError: Only triangular faces are supported.".

Thanks in advance.

**Comment by zhhiyuan** [comment]
@MoTahoun 
It's been a long time and I've forgotten the details, but maybe what you need to do is locate the code where the error occurred and annotated it.
