### ISSUE TITLE
Corrupted shard files in MegaPose-GSO dataset

### ISSUE THREAD

**Issue by sh8** [thodan/bop_toolkit#96]
I downloaded the shard files by following the instructions in [this link](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_challenge_2023_training_datasets.md), however, these shard files (shard-000101.tar, shard-000102.tar, shard-000108.tar, and shard-000114.tar) seem corrupted and have only 1KB.  

Could you please replace them with working versions when you get a chance? I've been trying to convert the original MegaPose-GSO dataset, but haven't had much luck.

Thank you!

**Comment by thodan** [comment]
@sh8 thanks for letting us know about this issue. We've re-uploaded the 4 tar files you mentioned. All files should be good now -- please let us know if you find any other problem.

**Comment by sh8** [comment]
Thank you so much for the quick fix!

**Comment by zuodexin** [comment]
I still found these mentioned file corrupted in the [GSO dataset](https://huggingface.co/datasets/bop-benchmark/datasets/tree/main/MegaPose-GSO), somthing wrong?

**Comment by nv-nguyen** [comment]
Hi @zuodexin, the issue is solved now. Please re-download and let us know if the issue still persists!

**Comment by zuodexin** [comment]
Thanks so much for the quick fix! Every file looks fine except this one [shard-000101.tar](https://huggingface.co/datasets/bop-benchmark/datasets/blob/main/MegaPose-GSO/shard-000101.tar) now.

**Comment by nv-nguyen** [comment]
@zuodexin I am not sure what is the difference but it seems that you are not using the same link as in [our tutorial](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_challenge_2023_training_datasets.md).

Our link is defined with `resolve/main` while your link is defined with `blob/main`.

Using our link yields indeed broken files while using our link downloads correct files. Please use [this link](https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/MegaPose-GSO/shard-000101.tar) instead.

**Comment by zuodexin** [comment]
problem solved
