### ISSUE TITLE
Corrupted shard file in MegaPose-ShapeNetCore dataset

### ISSUE THREAD

**Issue by zakharos** [thodan/bop_toolkit#97]
Hi @thodan!

Similarly to #96, the `shard-000701.tar` file ([link](https://bop.felk.cvut.cz/media/data/bop_datasets/bop23_datasets/megapose-shapenet/train_pbr_web/shard-000701.tar
)) in the MegaPose-ShapeNetCore dataset is only 1kB. Could you please replace it?

Thank you!

**Comment by ylabbe** [comment]
It will soon be uploaded on the bop website. In the meantime you can use this link https://www.dropbox.com/s/i21ty9c62cxtipf/shard-000701.tar?dl=0 to download the missing shard.

**Comment by thodan** [comment]
The tar file is now re-uploaded to the BOP server. Thanks!

**Comment by zakharos** [comment]
That's great, thanks a lot!
