### ISSUE TITLE
eval_bop22_coco.py Error

### ISSUE THREAD

**Issue by malenickymartin** [thodan/bop_toolkit#99]
I ran into a problem when I tried to run scripts/eval_bop22_coco.py. The problem seems to be [here](https://github.com/thodan/bop_toolkit/blob/37d79c4c5fb027da92bc40f36b82ea9b7b197f1d/scripts/eval_bop22_coco.py#L142). I am using pycocotools version 2.0.6, but even older versions support only file name as input to COCO. Has anyone successfully used this script?

**Comment by MartinSmeyer** [comment]
Hey,
We have patched the pycocotools. If you install the bop_toolkit dependencies in requirements.txt you will obtain the correct version from

https://github.com/MartinSmeyer/cocoapi

The script is used for the official BOP evaluations.
